# ASP.NET Core SOME CHANGE
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: Development
  jobs:
  - job: Development
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet build src --configuration $(buildConfiguration)
      displayName: 'Build'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'src/PocRandD.Test/PocRandD.Test.csproj'
      displayName: 'Unit_Tests'
    - script: sudo dotnet tool install --tool-path=/usr/bin dotnet-sonarscanner --version 4.10.0
      displayName: 'Static_Analysis__InstallSonnarScanner'
    - script: sudo dotnet sonarscanner begin /o:gerardoat /k:gerardoat_integracionpipelines /d:sonar.host.url=https://sonarcloud.io /version:$(Build.SourceVersion)
      displayName: 'Static_Analysis__BeginAnalysis'
    - script: sudo dotnet build src --configuration Release
      displayName: 'Static_Analysis__Building'
    - script: sudo SONAR_TOKEN=aff7a6afb8e4861ffd38a5ad975672f58598658a dotnet sonarscanner end
      displayName: 'Static_Analysis__EndAnalysis'
    - task: DotNetCoreCLI@2
      displayName: 'Create the Publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'src/PocRandD/PocRandD.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      condition: succeededOrFailed()
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Azure AppService'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'SuscripcionMaru'
        appType: 'webAppLinux'
        WebAppName: 'pocselenium'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|3.1'
  - job: WindowsSteps
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'src/PocRandD.SeleniumTest/PocRandD.SeleniumTest.csproj'
      displayName: 'FunctionalTests'
  - job: LinuxSteps
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Performance_Tests
      displayName: 'Performance_Tests'
    - script: echo Delete_Dev_Publish
      displayName: 'Delete_Dev_Publish'

- stage: QA
  jobs:
  - job: QA
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Publish_QA
      displayName: 'Publish_QA'
  
- stage: UAT
  jobs:
  - job: QA
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Publish_UAT
      displayName: 'Publish_UAT'
